name: Example Validation

on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
        description: 'Module name to validate'
      example:
        required: true
        type: string
        description: 'Example type (basic, advanced, complete)'
      path:
        required: true
        type: string
        description: 'Path to the example directory'

jobs:
  validate-example:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 'latest'
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.VTD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.VTD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Terraform Init
      working-directory: ${{ inputs.path }}
      run: terraform init -upgrade
      
    - name: Terraform Validate
      working-directory: ${{ inputs.path }}
      run: terraform validate -no-color
      
    - name: Terraform Plan
      working-directory: ${{ inputs.path }}
      run: |
        terraform plan -no-color -out=tfplan
        echo "## 🧾 Terraform Plan Summary for ${{ inputs.module }} - ${{ inputs.example }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        terraform show -no-color tfplan >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
      
    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: plan-${{ inputs.module }}-${{ inputs.example }}
        path: ${{ inputs.path }}/tfplan
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = '${{ inputs.path }}/tfplan';
          
          if (fs.existsSync(path)) {
            const planOutput = execSync('terraform show -no-color tfplan', { cwd: '${{ inputs.path }}' }).toString();
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🧾 Terraform Plan Summary for ${{ inputs.module }} - ${{ inputs.example }}
              
              **Status:** ✅ Plan validation successful
              **Module:** ${{ inputs.module }}
              **Example:** ${{ inputs.example }}
              
              <details>
              <summary>View Plan Details</summary>
              
              \`\`\`hcl
              ${planOutput}
              \`\`\`
              </details>`
            });
          }
          
    - name: Summary Check
      run: |
        echo "✅ Example validation completed successfully"
        echo "📋 Module: ${{ inputs.module }}"
        echo "📁 Example: ${{ inputs.example }}"
        echo "🔧 Path: ${{ inputs.path }}"