name: Simple Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-basic:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 'latest'
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.VTD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.VTD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Test VPC Basic Example
      working-directory: modules/vpc/examples/basic
      run: |
        terraform init -upgrade
        terraform validate
        terraform plan -no-color
        
    - name: Test EC2 Basic Example
      working-directory: modules/ec2/examples/basic
      run: |
        terraform init -upgrade
        terraform validate
        terraform plan -no-color
        
    - name: Test Lambda Basic Example
      working-directory: modules/lambda/examples/basic
      run: |
        terraform init -upgrade
        terraform validate
        terraform plan -no-color
        
    - name: Test S3 Basic Example
      working-directory: modules/s3/examples/basic
      run: |
        terraform init -upgrade
        terraform validate
        terraform plan -no-color